/**
 * Sector mapping for major NSE stocks.
 * Source: NSE sector indices (Nifty IT, Nifty Bank, Nifty Pharma, etc.)
 * Covers Nifty 50, Nifty Next 50, and other widely traded stocks.
 */
export const SECTOR_MAP: Record<string, string> = {
  // === IT ===
  TCS: 'IT',
  INFY: 'IT',
  HCLTECH: 'IT',
  WIPRO: 'IT',
  TECHM: 'IT',
  LTIM: 'IT',
  MPHASIS: 'IT',
  COFORGE: 'IT',
  PERSISTENT: 'IT',
  LTTS: 'IT',
  OFSS: 'IT',
  TATAELXSI: 'IT',
  BIRLASOFT: 'IT',
  ZENSAR: 'IT',
  MASTEK: 'IT',
  CYIENT: 'IT',
  HAPPSTMNDS: 'IT',
  KPITTECH: 'IT',
  ROUTE: 'IT',
  SONATSOFTW: 'IT',
  NEWGEN: 'IT',
  INTELLECT: 'IT',

  // === Banking ===
  HDFCBANK: 'Banking',
  ICICIBANK: 'Banking',
  KOTAKBANK: 'Banking',
  SBIN: 'Banking',
  AXISBANK: 'Banking',
  INDUSINDBK: 'Banking',
  BANKBARODA: 'Banking',
  PNB: 'Banking',
  CANBK: 'Banking',
  UNIONBANK: 'Banking',
  IDFCFIRSTB: 'Banking',
  FEDERALBNK: 'Banking',
  BANDHANBNK: 'Banking',
  AUBANK: 'Banking',
  RBLBANK: 'Banking',
  IDBI: 'Banking',
  IOB: 'Banking',
  INDIANB: 'Banking',
  CENTRALBK: 'Banking',
  UCOBANK: 'Banking',
  BANKINDIA: 'Banking',
  MAHABANK: 'Banking',
  PSB: 'Banking',
  J_KBANK: 'Banking',
  KARURVYSYA: 'Banking',
  CSBBANK: 'Banking',
  DCBBANK: 'Banking',
  SOUTHBANK: 'Banking',

  // === Financial Services (NBFC, Insurance, AMC) ===
  BAJFINANCE: 'Financial Services',
  BAJAJFINSV: 'Financial Services',
  HDFCLIFE: 'Financial Services',
  SBILIFE: 'Financial Services',
  ICICIPRULI: 'Financial Services',
  ICICIGI: 'Financial Services',
  CHOLAFIN: 'Financial Services',
  SHRIRAMFIN: 'Financial Services',
  MUTHOOTFIN: 'Financial Services',
  M_MFIN: 'Financial Services',
  MANAPPURAM: 'Financial Services',
  POONAWALLA: 'Financial Services',
  LICHSGFIN: 'Financial Services',
  RECLTD: 'Financial Services',
  PFC: 'Financial Services',
  IRFC: 'Financial Services',
  CAMS: 'Financial Services',
  CDSL: 'Financial Services',
  BSE: 'Financial Services',
  MCX: 'Financial Services',
  NIACL: 'Financial Services',
  GICRE: 'Financial Services',
  STARHEALTH: 'Financial Services',
  NYKAA: 'Financial Services',
  PAYTM: 'Financial Services',
  POLICYBZR: 'Financial Services',
  ANGELONE: 'Financial Services',
  MOTILALOFS: 'Financial Services',
  IIFL: 'Financial Services',
  NAM_INDIA: 'Financial Services',
  SUNDARMFIN: 'Financial Services',
  CANFINHOME: 'Financial Services',
  HUDCO: 'Financial Services',
  ABSLAMC: 'Financial Services',

  // === Pharma & Healthcare ===
  SUNPHARMA: 'Pharma',
  DRREDDY: 'Pharma',
  CIPLA: 'Pharma',
  DIVISLAB: 'Pharma',
  APOLLOHOSP: 'Healthcare',
  MAXHEALTH: 'Healthcare',
  MANKIND: 'Pharma',
  TORNTPHARM: 'Pharma',
  LUPIN: 'Pharma',
  AUROPHARMA: 'Pharma',
  ZYDUSLIFE: 'Pharma',
  BIOCON: 'Pharma',
  ALKEM: 'Pharma',
  IPCALAB: 'Pharma',
  NATCOPHARMA: 'Pharma',
  LAURUSLABS: 'Pharma',
  GLENMARK: 'Pharma',
  ABBOTINDIA: 'Pharma',
  SYNGENE: 'Pharma',
  GLAND: 'Pharma',
  LALPATHLAB: 'Healthcare',
  METROPOLIS: 'Healthcare',
  FORTIS: 'Healthcare',
  MEDANTA: 'Healthcare',
  YATHARTH: 'Healthcare',
  RAINBOW: 'Healthcare',
  KIMS: 'Healthcare',
  GLOBALHEAL: 'Healthcare',

  // === Auto ===
  MARUTI: 'Auto',
  TATAMOTORS: 'Auto',
  M_M: 'Auto',
  BAJAJ_AUTO: 'Auto',
  EICHERMOT: 'Auto',
  HEROMOTOCO: 'Auto',
  ASHOKLEY: 'Auto',
  TVSMOTOR: 'Auto',
  BALKRISIND: 'Auto',
  MOTHERSON: 'Auto',
  BOSCHLTD: 'Auto',
  MRF: 'Auto',
  BHARATFORG: 'Auto',
  EXIDEIND: 'Auto',
  AMARAJABAT: 'Auto',
  APOLLOTYRE: 'Auto',
  CEATLTD: 'Auto',
  ENDURANCE: 'Auto',
  SONACOMS: 'Auto',
  SAMVARDHNA: 'Auto',
  TIINDIA: 'Auto',
  SUNDRMFAST: 'Auto',
  OLECTRA: 'Auto',

  // === FMCG ===
  HINDUNILVR: 'FMCG',
  ITC: 'FMCG',
  NESTLEIND: 'FMCG',
  BRITANNIA: 'FMCG',
  TATACONSUM: 'FMCG',
  DABUR: 'FMCG',
  GODREJCP: 'FMCG',
  MARICO: 'FMCG',
  COLPAL: 'FMCG',
  EMAMILTD: 'FMCG',
  PGHH: 'FMCG',
  UBL: 'FMCG',
  MCDOWELL_N: 'FMCG',
  VBL: 'FMCG',
  RADICO: 'FMCG',
  ZOMATO: 'FMCG',
  DEVYANI: 'FMCG',
  JUBLFOOD: 'FMCG',
  TRENT: 'FMCG',
  DMART: 'FMCG',
  BIKAJI: 'FMCG',
  PATANJALI: 'FMCG',
  HONASA: 'FMCG',

  // === Energy / Oil & Gas ===
  RELIANCE: 'Oil & Gas',
  ONGC: 'Oil & Gas',
  IOC: 'Oil & Gas',
  BPCL: 'Oil & Gas',
  HINDPETRO: 'Oil & Gas',
  GAIL: 'Oil & Gas',
  PETRONET: 'Oil & Gas',
  OIL: 'Oil & Gas',
  MGL: 'Oil & Gas',
  IGL: 'Oil & Gas',
  GUJGASLTD: 'Oil & Gas',
  AEGISCHEM: 'Oil & Gas',
  CASTROLIND: 'Oil & Gas',
  GSPL: 'Oil & Gas',

  // === Metals & Mining ===
  TATASTEEL: 'Metals',
  HINDALCO: 'Metals',
  JSWSTEEL: 'Metals',
  VEDL: 'Metals',
  COALINDIA: 'Metals',
  NMDC: 'Metals',
  NATIONALUM: 'Metals',
  SAIL: 'Metals',
  JINDALSTEL: 'Metals',
  HINDZINC: 'Metals',
  APLAPOLLO: 'Metals',
  RATNAMANI: 'Metals',
  MOIL: 'Metals',
  WELCORP: 'Metals',

  // === Power & Utilities ===
  NTPC: 'Power',
  POWERGRID: 'Power',
  ADANIGREEN: 'Power',
  ADANIENSOL: 'Power',
  TATAPOWER: 'Power',
  NHPC: 'Power',
  SJVN: 'Power',
  TORNTPOWER: 'Power',
  CESC: 'Power',
  JSL: 'Power',
  JSWENERGY: 'Power',
  IREDA: 'Power',

  // === Telecom ===
  BHARTIARTL: 'Telecom',
  IDEA: 'Telecom',
  INDIAMART: 'Telecom',
  TATACOMM: 'Telecom',

  // === Realty ===
  DLF: 'Realty',
  GODREJPROP: 'Realty',
  OBEROIRLTY: 'Realty',
  PRESTIGE: 'Realty',
  LODHA: 'Realty',
  PHOENIXLTD: 'Realty',
  BRIGADE: 'Realty',
  SOBHA: 'Realty',
  SUNTECK: 'Realty',
  MAHLIFE: 'Realty',
  SIGNATURE: 'Realty',

  // === Cement ===
  ULTRACEMCO: 'Cement',
  GRASIM: 'Cement',
  AMBUJACEM: 'Cement',
  SHREECEM: 'Cement',
  ACC: 'Cement',
  DALMIASUGAR: 'Cement',
  RAMCOCEM: 'Cement',
  JKCEMENT: 'Cement',
  BIRLACORPN: 'Cement',
  STARCEMENT: 'Cement',
  HEIDELBERG: 'Cement',
  JKLAKSHMI: 'Cement',
  DALBHARAT: 'Cement',
  NUVOCO: 'Cement',

  // === Infrastructure & Construction ===
  LT: 'Infrastructure',
  ADANIENT: 'Infrastructure',
  ADANIPORTS: 'Infrastructure',
  SIEMENS: 'Capital Goods',
  ABB: 'Capital Goods',
  HAL: 'Capital Goods',
  BEL: 'Capital Goods',
  BHEL: 'Capital Goods',
  THERMAX: 'Capital Goods',
  CUMMINSIND: 'Capital Goods',
  VOLTAS: 'Capital Goods',
  BLUESTARLT: 'Capital Goods',
  HAVELLS: 'Capital Goods',
  POLYCAB: 'Capital Goods',
  KEI: 'Capital Goods',
  KAYNES: 'Capital Goods',
  DIXON: 'Capital Goods',
  AFFLE: 'Capital Goods',
  GRINDWELL: 'Capital Goods',
  IRB: 'Infrastructure',
  KNR: 'Infrastructure',
  NBCC: 'Infrastructure',
  NCC: 'Infrastructure',
  PEL: 'Infrastructure',
  COCHINSHIP: 'Infrastructure',
  MAZAGONDOC: 'Infrastructure',
  GRSE: 'Infrastructure',
  BDL: 'Infrastructure',
  GARDENREACH: 'Infrastructure',

  // === Chemicals ===
  PIDILITIND: 'Chemicals',
  SRF: 'Chemicals',
  ATUL: 'Chemicals',
  DEEPAKNTR: 'Chemicals',
  NAVINFLUOR: 'Chemicals',
  CLEAN: 'Chemicals',
  FLUOROCHEM: 'Chemicals',
  TATACHEM: 'Chemicals',
  UPL: 'Chemicals',
  PI: 'Chemicals',
  BASF: 'Chemicals',
  SUMICHEM: 'Chemicals',
  AARTI: 'Chemicals',
  FINEORG: 'Chemicals',
  ALKYLAMINE: 'Chemicals',
  GALAXYSURF: 'Chemicals',
  ANANTRAJ: 'Chemicals',

  // === Consumer Durables ===
  TITAN: 'Consumer Durables',
  PAGEIND: 'Consumer Durables',
  WHIRLPOOL: 'Consumer Durables',
  CROMPTON: 'Consumer Durables',
  BATAINDIA: 'Consumer Durables',
  RAJESHEXPO: 'Consumer Durables',
  BLUESTAR: 'Consumer Durables',
  VGUARD: 'Consumer Durables',
  RELAXO: 'Consumer Durables',
  CENTURYPLY: 'Consumer Durables',
  KAJARIACER: 'Consumer Durables',
  ORIENTELEC: 'Consumer Durables',
  SAPPHIRE: 'Consumer Durables',
  AMBER: 'Consumer Durables',

  // === Media & Entertainment ===
  ZEEL: 'Media',
  PVR: 'Media',
  SUNTV: 'Media',
  NETWORK18: 'Media',
  TV18BRDCST: 'Media',
  SAREGAMA: 'Media',
  NAZARA: 'Media',
  TIPS: 'Media',

  // === Textiles ===
  RAYMOND: 'Textiles',
  ARVIND: 'Textiles',
  TRIDENT: 'Textiles',
  WELSPUNLIV: 'Textiles',
  KPRMILL: 'Textiles',
  GOKEX: 'Textiles',
  VRLLOG: 'Textiles',

  // === Miscellaneous / Conglomerates ===
  IRCTC: 'Infrastructure',
  INDIANHOTL: 'Consumer Durables',
  LEMON: 'Consumer Durables',
};
